# Generated by Django 2.2 on 2019-08-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('sex', models.CharField(choices=[('male', 'man'), ('female', 'woman')], default='man', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
    ]
